# Generated by Django 3.2.8 on 2021-12-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoFormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('objetivos', models.TextField(null=True)),
                ('experiencias', models.TextField(null=True)),
                ('contenido', models.TextField(null=True)),
                ('recursosymateriales', models.TextField(blank=True, null=True)),
                ('EstrategiasEvaluacion', models.TextField(null=True)),
                ('FechaInicio', models.DateField()),
                ('FechaFin', models.DateField()),
                ('RefBiblio', models.TextField(blank=True, null=True)),
                ('UtilidadOportunidad', models.TextField(null=True)),
                ('CupoMax', models.CharField(max_length=3)),
                ('ReqAcreditacion', models.TextField(null=True)),
                ('ExperienciasInst', models.TextField(null=True)),
                ('DirigidoA', models.TextField(null=True)),
                ('ReqParticipacion', models.TextField(null=True)),
                ('CurriculumInst', models.TextField(null=True)),
                ('Autofinanciamiento', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
