# Generated by Django 3.2.8 on 2021-12-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventoformativo',
            old_name='nombre',
            new_name='name',
        ),
    ]
