# Generated by Django 3.2.8 on 2021-12-01 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_nombre_eventoformativo_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventoFormativo',
            new_name='Evento',
        ),
    ]
