# Generated by Django 3.2.8 on 2021-12-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_eventoformativo_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='evento',
            name='TipoEventos',
            field=models.CharField(choices=[('Diplomado', 'Diplomado'), ('Curso', 'Curso'), ('Taller', 'Taller'), ('Programa Especial', 'Programa Especial')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='modalidad',
            field=models.CharField(choices=[('Diplomado', 'Diplomado'), ('Curso', 'Curso'), ('Taller', 'Taller'), ('Programa Especial', 'Programa Especial')], max_length=30, null=True),
        ),
    ]
