# Generated by Django 3.2.8 on 2021-12-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_evento_modalidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Autofinanciamiento',
            new_name='Capacidad_de_utofinanciamiento',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='CupoMax',
            new_name='Cupo_Maximo',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='CurriculumInst',
            new_name='Curriculum_de_los_Instructores',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='DirigidoA',
            new_name='Dirigido_a',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='EstrategiasEvaluacion',
            new_name='Estrategias_de_Evaluacion',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='ExperienciasInst',
            new_name='Experiencia_y_pericia_de_Instructores',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='FechaFin',
            new_name='Fecha_de_Fin',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='FechaInicio',
            new_name='Fecha_de_Inicio',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='RefBiblio',
            new_name='Referencias_y_bibliografia',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='ReqAcreditacion',
            new_name='Requisistos_de_Acreditacion',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='ReqParticipacion',
            new_name='Requisitos_de_Participacion',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='UtilidadOportunidad',
            new_name='Utilidad_y_Oportunidad_del_programa',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='recursosymateriales',
            new_name='recursos_y_materiales',
        ),
    ]
